import { DM_Sans } from "next/font/google";
import "./globals.css";

//COMPONENT
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition"

const dm = DM_Sans({ subsets: ["latin"], weight:["100", "200", "300", "400", "500", "600", "700"],
  variable: '--font-DmSans'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dm.variable}> 
        <Header />
        <PageTransition>
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
